export const LOADING = 'LOADING';
export const API_CALL = 'API_CALL';
export const SEARCH_ON_SUBMIT = 'SEARCH_ON_SUBMIT';
export const SAVE_IMAGE = 'SAVE_IMAGE';
export const SELECT_IMAGE = 'SELECT_IMAGE';
export const DISSELECT_IMAGE = 'DISSELECT_IMAGE';
export const SAVE_IMAGES = 'SAVE_IMAGES';
export const SELECT_GRID = 'SELECT_GRID';
export const DISSELECT_GRID = 'DISSELECT_GRID';
export const SELECT_NEW_FEATURE = 'SELECT_NEW_FEATURE';
export const GET_PAGE_COUNT = 'GET_PAGE_COUNT';
export const SELECT_PAGE = 'SELECT_PAGE';
export const SLIDE_PAGE_SETUP = 'SLIDE_PAGE_SETUP';

export const featureGroups = {
	POPULAR: 'POPULAR',
	HIGHEST_RATED: 'HIGHEST_RATED',
	UPCOMING: 'UPCOMING',
	EDITORS: 'EDITORS',
	FRESH_TODAY: 'FRESH_TODAY',
	FRESH_YESTERDAY: 'FRESH_YESTERDAY',
	FRESH_WEEK: 'FRESH_WEEK'
}