export const LOADING = 'LOADING';
export const API_CALL = 'API_CALL';
export const SELECT_NEW_SORTING = 'SELECT_NEW_SORTING';

export const sortingGroups = {
	MOST_POPULAR: 'MOST_POPULAR',
	HIGHEST_RATED: 'HIGHEST_RATED',
	UPCOMING: 'UPCOMING',
	EDITORS_PICKS: 'EDITORS_PICKS',
	FRESH_TODAY: 'FRESH_TODAY',
	FRESH_YESTERDAY: 'FRESH_YESTERDAY',
	FRESH_THIS_WEEK: 'FRESH_THIS_WEEK'
}