export const LOADING = 'LOADING';
export const API_CALL = 'API_CALL';
export const SAVE_IMAGE = 'SAVE_IMAGE';
export const SAVE_IMAGES = 'SAVE_IMAGES';
export const SELECT_NEW_FEATURE = 'SELECT_NEW_FEATURE';
export const GET_PAGE_COUNT = 'GET_PAGE_COUNT';
export const SELECT_PAGE = 'SELECT_PAGE';

export const featureGroups = {
	POPULAR: 'POPULAR',
	HIGHEST_RATED: 'HIGHEST_RATED',
	UPCOMING: 'UPCOMING',
	EDITORS: 'EDITORS',
	FRESH_TODAY: 'FRESH_TODAY',
	FRESH_YESTERDAY: 'FRESH_YESTERDAY',
	FRESH_WEEK: 'FRESH_WEEK'
}